---
require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sequel

AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "_snippets/*"
  Include:
    - "Gemfile"
    - "Rakefile"

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "Rakefile"
  AllowedMethods:
    - namespace
    - task

Naming/RescuedExceptionsVariableName:
  Enabled: false

# Ignore use of OpenStruct for representers
Style/OpenStructUse:
  Enabled: false
