name: API continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  api_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: ["3.3.5"]

    runs-on: ${{ matrix.os }}-latest

    env:
      BUNDLE_WITHOUT: production
      RACK_ENV: test
      DATABASE_URL: sqlite://db/local/test.db

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Create database directory
        run: |
          mkdir -p db/local
          touch db/local/test.db
      - name: Create secrets.yml
        run: |
          mkdir -p config
          cat > config/secrets.yml << EOL
          ---
          development:
            DB_FILENAME: db/local/dev.db
            OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
            GOOGLE_CLOUD_API_TOKEN: "${{ secrets.GOOGLE_CLOUD_API_TOKEN }}"
            SESSION_SECRET: "${{ secrets.SESSION_SECRET }}"
          test:
            DB_FILENAME: db/local/test.db
            OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
            GOOGLE_CLOUD_API_TOKEN: "${{ secrets.GOOGLE_CLOUD_API_TOKEN }}"
            SESSION_SECRET: "${{ secrets.SESSION_SECRET }}"
          production:
            OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
            GOOGLE_CLOUD_API_TOKEN: "${{ secrets.GOOGLE_CLOUD_API_TOKEN }}"
            SESSION_SECRET: "${{ secrets.SESSION_SECRET }}"
          EOL
      - name: Setup test database
        run: bundle exec rake db:migrate

      - name: Copy VCR cassettes from fixtures
        run: |
          mkdir -p spec/fixtures/cassettes
          cp spec/fixtures/*.yml spec/fixtures/cassettes/ || true
      - name: Run all specs
        run: bundle exec rake spec
