name: API continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  api_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: ["3.3.5"]

    runs-on: ${{ matrix.os }}-latest

    env:
      BUNDLE_WITHOUT: production
      RACK_ENV: test
      DATABASE_URL: sqlite://db/local/test.db

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Create database directory
        run: |
          mkdir -p db/local
          touch db/local/test.db

      - name: Create secrets.yml
        run: |
          mkdir -p config
          echo "---" > config/secrets.yml
          echo "test:" >> config/secrets.yml
          echo "  DB_FILENAME: db/local/test.db" >> config/secrets.yml
          echo "  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}" >> config/secrets.yml
          echo "  GOOGLE_CLOUD_API_TOKEN: ${{ secrets.GOOGLE_CLOUD_API_TOKEN }}" >> config/secrets.yml
          echo "  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}" >> config/secrets.yml

      - name: Setup test database
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CLOUD_API_TOKEN: ${{ secrets.GOOGLE_CLOUD_API_TOKEN }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: bundle exec rake db:migrate

      - name: Run all specs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CLOUD_API_TOKEN: ${{ secrets.GOOGLE_CLOUD_API_TOKEN }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: bundle exec rake spec
